const watchNamesList = [
    "a.b.art",
    "A.Favre & Fils",
    "A.Lange & Söhne",
    "A.Mantei",
    "A.Manzoni & Fils",
    "AATOS",
    "ABP Paris",
    "Accutron",
    "Aeronautica Militare",
    "Aerowatch",
    "Aigner",
    "AkriviA",
    "Akrone",
    "Akura",
    "Alain Silberstein",
    "Alcadus",
    "Alchemists",
    "Alessandro Baldieri",
    "Alexander Shorokhoff",
    "Alexandre Meerson",
    "Alfex",
    "Alfred Dunhill",
    "Alfred Rochat & Fils",
    "Alkin",
    "Alludens",
    "Aloha Watches",
    "Alpina",
    "Alsta",
    "Ancon",
    "Andersen Genève",
    "Andersmann",
    "Andreas Strehler",
    "Angelus",
    "Angular Momentum",
    "Anonimo",
    "Anstead",
    "Antoine Preziuso",
    "Anura Rafael",
    "Apple",
    "Aquadive",
    "Aquanautic",
    "Aquastar",
    "Arcadia",
    "Arcaido",
    "Archimede",
    "Arctic",
    "Arctos",
    "Aristo",
    "Arlanch",
    "Armand Nicolet",
    "Armani",
    "Armida",
    "Armin Strom",
    "Armourlite",
    "Arnold & Son",
    "Arnold Schwarzenegger",
    "Artisanal",
    "Artya",
    "Askania",
    "Aspen",
    "Astor+Banks",
    "Astos",
    "Atelier de Chronometrie",
    "Atelier Millesime",
    "Ateliers deMonaco",
    "Ather",
    "Atlantic",
    "AttoVerticale",
    "Attra",
    "Audaz",
    "Audemars Piguet",
    "Auguste Reymond",
    "Auricoste",
    "Autodromo",
    "Avakian",
    "Avenir",
    "Aventi",
    "Avi-8",
    "Aviator",
    "Avier",
    "Axia Time",
    "Azimuth",
    "Azzaro",
    "B.R.M",
    "Ba111od",
    "Backes & Strauss",
    "Badollet",
    "Ball",
    "Ballast",
    "Balmain",
    "Bamford",
    "Bangalore Watch Company",
    "Barrelhand",
    "Bathys",
    "Baume",
    "Baume & Mercier",
    "Bausele",
    "Bavarian Crono",
    "BCHH",
    "Bedat & Co",
    "Beijing Watch Factory",
    "Bell & Ross",
    "Belmoto",
    "Benarus",
    "Benrus",
    "Benzinger",
    "Berne",
    "Bernhardt",
    "Bertolucci",
    "Beuchat",
    "Bexei",
    "Bianci",
    "Biatec",
    "Bifora",
    "Black Belt",
    "Black-Out Concept",
    "Blacksand",
    "Blancarre",
    "Blancier",
    "Blancpain",
    "blu",
    "BMW",
    "BNB Concept",
    "Boegli",
    "Bogner Time",
    "Boldr",
    "Bomberg",
    "Botta",
    "Boucheron",
    "Bovet",
    "Braun",
    "Bravur",
    "Breguet",
    "Breil",
    "Breitling",
    "Brellum",
    "Bremont",
    "Breva",
    "Brew",
    "Briston",
    "BRM",
    "Bruggler",
    "Bruno Söhnle",
    "Buben & Zorweg",
    "Buccellati",
    "Bulbul",
    "Bulgari",
    "Bulova",
    "Bunz",
    "Burberry",
    "Burberry",
    "BVLGARI",
    "BWC-Swiss",
    "C.H. Wolf",
    "C3H5N3O9",
    "Cabestan",
    "Cacheux",
    "Cadence",
    "Camel Active",
    "Camille Fournet",
    "Candino",
    "Carl Edmond",
    "Carl F. Bucherer",
    "Carl Suchy & Sohne",
    "Carlo Ferrara",
    "Carlo Maroni",
    "Cartier",
    "Casio",
    "Catamaran",
    "Catorex",
    "Cattin",
    "Cavenago",
    "CCCP",
    "Cecil Purnell",
    "Celadon",
    "Century",
    "Cerruti",
    "Certina",
    "Chanel",
    "Charmex",
    "Charriol",
    "Chase-Durer",
    "Chaumet",
    "Chopard",
    "Chouette",
    "Chris Benz",
    "Christiaan Van Der Klaauw",
    "Christophe Claret",
    "Christopher Ward",
    "Chronographe Suisse",
    "Chronometrie Ferdinand Berthoud",
    "Chronoswiss",
    "Churchill Watch Company",
    "Churpfälzische Uhrenmanufaktur",
    "Circula",
    "Citizen",
    "Citizen Campanola",
    "ck Calvin Klein",
    "Claude Bernard",
    "Claude Meylan",
    "Clerc",
    "Click",
    "CODE41",
    "Codek",
    "Collins Watch Company",
    "Concept Creations",
    "Concord",
    "Condor",
    "Confrerie Horlogere",
    "Cornehl",
    "Cortébert",
    "Corum",
    "Crafter Blue",
    "Creo",
    "Crepas",
    "Crockett & Jones",
    "Cronus",
    "Cross",
    "Croton",
    "CT Scuderia",
    "Cuervo y Sobrinos",
    "Culem",
    "Cuntur",
    "Cvstos",
    "CWC",
    "CX Swiss Military Watch",
    "Cyclos",
    "Cyma",
    "Cyrus",
    "Czapek & Cie",
    "D. Candaux",
    "D. Dornblüth & Sohn",
    "Da Vindice",
    "Damasko",
    "Daniel Roth",
    "Daniel Strom",
    "David Rutten",
    "David Yurman",
    "Davidoff",
    "Davosa",
    "De Bethune",
    "De Grisogono",
    "De Tournemire",
    "Debaufre",
    "Decade",
    "Dedegumo",
    "Deep Blue",
    "Defakto",
    "Dekla",
    "DeLaCour",
    "DeLaneau",
    "Delma",
    "Demence",
    "Dent",
    "Detroit Watch Company",
    "Devon",
    "Devon Works",
    "Dewitt",
    "DeWitt",
    "Dexter Sinister",
    "Diesel",
    "Dietrich",
    "Dievas",
    "Dior",
    "Direnzo",
    "Division Furtive",
    "Dodane",
    "Dolce & Gabbana",
    "Dominique Renaud",
    "Done",
    "Doplr",
    "Doxa",
    "Dreyfuss & Co",
    "Dubey & Schaldenbrand",
    "DuBois 1785",
    "DuBois et fils",
    "Duesenberg",
    "Dufa",
    "Dufeau",
    "DuFrane",
    "Dugena",
    "Dunhill",
    "Dürmeister",
    "DWATCH",
    "Dwiss",
    "Dzmitry Samal",
    "E.C. Andersson",
    "Earnshaw",
    "Ebel",
    "Eberhard & Co.",
    "Edmond",
    "Edouard Lauzieres",
    "Edox",
    "Egard",
    "EHF Horlogere",
    "Eichmüller",
    "Election",
    "Electricianz",
    "Elgin",
    "Ellicott",
    "Elliot Brown",
    "Elysee",
    "Ematelier",
    "EMG",
    "Emile Chouriet",
    "Emmanuel Bouchet",
    "Emporio Armani",
    "Engelhardt",
    "Enicar",
    "Ennebi",
    "Enzo Mechana",
    "Eone",
    "Epos",
    "Epson",
    "Equipe",
    "Ernest Borel",
    "Ernst Benz",
    "Erwin Sattler",
    "Esprit",
    "Essex",
    "Eterna",
    "Eulit",
    "Eulux",
    "Eva Leube",
    "Everest",
    "Evisu",
    "Eza",
    "Ezteem",
    "F.P. Journe",
    "Faberge",
    "Farer",
    "Favre-Leuba",
    "Fears",
    "Feldo",
    "Fendi",
    "Ferragamo",
    "Festina",
    "Festina",
    "Fine Watches Berlin FWB",
    "Fiona Kruger",
    "Fiorucci",
    "Fitbit",
    "Fiyta",
    "Fluco",
    "Fonderie 47",
    "Formex",
    "Fortis",
    "Forum",
    "Fossil",
    "Franc Vila",
    "Franck Dubarry",
    "Franck Muller",
    "Frederic Jouvenot",
    "Frederique Constant",
    "FUGUE",
    "Fullspot",
    "Gaga Milano",
    "Gagarin",
    "Gallet",
    "Gant",
    "Ganymede",
    "Gardé",
    "Garmin",
    "Garrick",
    "Gavox",
    "Genesis",
    "Genus",
    "Geoffrey Roth",
    "Georges V",
    "Gerald Genta",
    "Gerge",
    "Germano & Walter",
    "Gevril",
    "Gigandet",
    "Gilt",
    "Giorgio Piola",
    "Girard Perregaux",
    "Giuliano Mazzuoli",
    "Glam Rock",
    "Glashutte Original",
    "Glycine",
    "Gorilla",
    "Graf",
    "Graham",
    "Grand Seiko",
    "Greco",
    "Greiner",
    "Greubel Forsey",
    "Gronefeld",
    "Grovana",
    "Gruen",
    "Gruppo Gamma",
    "GSX",
    "GUB Glashütte",
    "Gubelin",
    "Gucci",
    "Guer",
    "Guess",
    "Guinand",
    "Gustafsson & Sjogren",
    "Guy Laroche",
    "H.I.D. Watch",
    "H.Moser & Cie.",
    "H20",
    "Habring",
    "Hacher",
    "Haemmer",
    "Hagal",
    "Hajime Asaoka",
    "Halda",
    "Haldimann",
    "Haldor",
    "Halios",
    "Hamilton",
    "Hanhart",
    "Harry Winston",
    "Harwood",
    "Hautlence",
    "HD3",
    "Hebdomas",
    "Hebe",
    "Helix",
    "Helson",
    "Helvetia",
    "Hemel",
    "Hentschel Hamburg",
    "Heritage Watch Manufactory",
    "Hermès",
    "Herzog",
    "Heuer",
    "Heure Raffinee",
    "Hexa",
    "Hirsch",
    "Hked watches",
    "Hoptroff",
    "Horage",
    "Horus",
    "Hotblack London",
    "Hublot",
    "Hugo Boss",
    "Hyetis",
    "Hysek",
    "HYT",
    "I-Toc",
    "Ice Watch",
    "ICON",
    "Ikepod",
    "Illinois",
    "Immersion",
    "Individual Design",
    "Ingersoll",
    "Invicta",
    "Iron Annie",
    "Issey Miyake",
    "ITAnano",
    "Itay Noy",
    "IWC",
    "J-B Viot",
    "J.N. Shapiro",
    "Jacob & Co.",
    "Jacob & Co.",
    "Jacques Etoile",
    "Jacques Lemans",
    "Jaeger-Benzinger",
    "Jaeger-LeCoultre",
    "Jaermann & Stübi",
    "Jaquet-Droz",
    "JB Gioacchino",
    "Jean d’Eve",
    "Jean Dunand",
    "Jean Lassale",
    "Jean Marcel",
    "JeanRichard",
    "Jenny",
    "Jiusko",
    "John Isaac Geneve",
    "Joop",
    "Jordi",
    "Jorg Gray",
    "Jorg Hysek",
    "Jorg Schauer",
    "JS Watch",
    "Jules Jürgensen",
    "Julien Coudray 1518",
    "Julien de Bourg",
    "Junghans",
    "Junkers",
    "Juvenia",
    "Kairos",
    "Kamawatch",
    "Kari Voutilainen",
    "Karsten Fraessdorf",
    "Kazimon",
    "Keaton Myrick",
    "Kelek",
    "Kentex",
    "Kerbedanz",
    "KHS",
    "KHS-Watch",
    "Kienzle",
    "Klokers",
    "Kobold",
    "Konstantin Chaykin",
    "Korloff",
    "Korsbek",
    "Krayon",
    "Krieger",
    "Kronaby",
    "Kronsegler",
    "Kronos",
    "Kudoke",
    "L. Kendall",
    "L. Leroy",
    "L’Epee",
    "L&JR",
    "Laco",
    "Lacoste",
    "Ladoire",
    "Lancaster",
    "Lanco",
    "Lang & Heyne",
    "Lapizta",
    "Laurent Ferrier",
    "Laventure",
    "Leatherman",
    "Lebeau-Courally",
    "Lebois & Co",
    "Lecronos",
    "Le Forban",
    "Leg0",
    "Le Jour",
    "Lemania",
    "Leonidas",
    "Lepine Belharra",
    "Lesablier",
    "Lew & Huey",
    "LG",
    "Limes",
    "Linde Werdelin",
    "Lip",
    "Liv Watches",
    "Locman",
    "Loiseau",
    "Longines",
    "Longio",
    "Lorenz",
    "Lornet",
    "Lorus",
    "Lotus",
    "Louis Chevrolet",
    "Louis Erard",
    "Louis Moinet",
    "Louis Vuitton",
    "Louis XVI",
    "Lucien Piccard",
    "Lucien Rochat",
    "Ludovic Ballouard",
    "Lüm-Tec",
    "Luminox",
    "LumiSidus",
    "Lytt Labs",
    "M&M Swiss Watch",
    "Magellan",
    "Magrette",
    "Maitres du Temps",
    "Malchert",
    "ManchesterWatchWorks",
    "Manufacture Royale",
    "Marathon",
    "Marburger",
    "Marc Ecko",
    "Marcello C.",
    "MARCH LA.B",
    "Margi",
    "Marlboro",
    "Marnaut",
    "Martenero",
    "Martin Braun",
    "Marvin",
    "Maserati",
    "MAT",
    "Mathey-Tissot",
    "Mauboussin",
    "Maurice de Mauriac",
    "Maurice Lacroix",
    "Mauron Musy",
    "Mb&f",
    "MCT",
    "Meccaniche Veloci",
    "Meccaniche Veneziane",
    "Meistersinger",
    "Melbourne Watch Company",
    "Memorigin",
    "Memphis Belle",
    "Mercer",
    "Mercure",
    "Mermod Freres",
    "MetaWatch",
    "Meyers",
    "Michael Bastian",
    "Michael Bittel",
    "Michael Kors",
    "Michel Herbelin",
    "Michel Jordi",
    "Michele",
    "Michelsen",
    "Mido",
    "MIH",
    "Milleret",
    "Millesime",
    "Milus",
    "Minerva",
    "Ming",
    "Minus-8",
    "Minuteman",
    "MK II",
    "Molnar Fabry",
    "Momentum",
    "Momo Design",
    "Mondaine",
    "Mondia",
    "Monta",
    "Montana",
    "Montandon",
    "Montano",
    "Montblanc",
    "Montega",
    "Montegrappa",
    "Montrek",
    "Mooren",
    "Morellato",
    "Morgenwerk",
    "Moritz Grossmann",
    "Morpheus",
    "Moto Koure",
    "Motorola",
    "Movado",
    "MoVas",
    "Mr. Jones Watches",
    "MTM",
    "Muhle Glashutte",
    "Musk",
    "MVMT",
    "N.B. Yäeger",
    "N.O.A",
    "Nautica",
    "Nauticfish",
    "Nethuns",
    "Nevo",
    "New Orleans",
    "Niall",
    "Nico Gerard",
    "Nike",
    "Nina Ricci",
    "Nite",
    "Nivada",
    "Nivrel",
    "Nixon",
    "Nodus",
    "Nomad",
    "NOMOS",
    "NORD Zeitmaschine",
    "Norqain",
    "Nouvelle Horlogerie Calabrese (NHC)",
    "Nove",
    "NTH",
    "Nubeo",
    "Oak & Oscar",
    "Oakley",
    "Objest",
    "Ocean Crawler",
    "Ocean7",
    "Ochs und Junior",
    "ODM",
    "Officina del Tempo",
    "Olio",
    "Ollech & Wajs",
    "Omega",
    "Ophion",
    "Orator",
    "Orbita",
    "Orfina",
    "Orient",
    "Orion",
    "Oris",
    "Out Of Order",
    "OWC",
    "Pacardt",
    "Panerai",
    "Panzera",
    "Parmigiani Fleurier",
    "Patek Philippe",
    "Patton",
    "Paul Picot",
    "Pebble Smartwatches",
    "Pellikaan",
    "Pequignet",
    "Perigáum",
    "Perrelet",
    "Perrelet",
    "Perseo",
    "Peter Roberts",
    "Phantoms",
    "Phenomen",
    "Philip Stein",
    "Philip Watch",
    "Philippe Dufour",
    "Phosphor",
    "Piaget",
    "Pierre Balmain",
    "Pierre Cardin",
    "Pierre DeRoche",
    "Pierre Kunz",
    "Pita",
    "Polar",
    "Police",
    "Poljot",
    "Porsche Design",
    "Praesto",
    "Pramzius",
    "Prim",
    "Pro-Hunter",
    "Projects",
    "Prometheus",
    "Pryngeps",
    "Pulsar",
    "Puma",
    "QlockTwo",
    "Quinting",
    "R. Gauthier",
    "Rado",
    "Raidillon",
    "Rainer Brand",
    "Rainer Nienaber",
    "Raketa",
    "Ralf Tech",
    "Ralph Lauren",
    "Raven",
    "Raymond Weil",
    "Reactor",
    "Rebellion",
    "REC Watches",
    "Record",
    "Red Sea",
    "Red8",
    "Refined Hardware",
    "Reservoir",
    "Ressence",
    "Reuge",
    "Revelation",
    "Reverie",
    "Revue Thommen",
    "RGM",
    "Richard Mille",
    "Ril",
    "Rios1931",
    "Riskers",
    "Ritmo Mundo",
    "Roamer",
    "Robert Lighton",
    "Rodolphe",
    "Roger Dubuis",
    "Roger Smith",
    "Rogue Warrior Watch",
    "Rolex",
    "Rolf Lang",
    "Romain Jerome",
    "Ronkko",
    "Roshan Martin",
    "Rossling",
    "Rotary",
    "Rothenschild",
    "Roue",
    "ROWI",
    "Rpaige",
    "RSW",
    "Ryser Kentfield",
    "S.Oliver",
    "S.T. Dupont",
    "Sablier",
    "Salvatore Ferragamo",
    "Samsung",
    "Sandoz",
    "Sarcar",
    "SARO-Gem",
    "Sarpaneva",
    "Sartory-Billard",
    "Savoy",
    "Scalfaro",
    "Schauer",
    "Schaumburg",
    "Schofield",
    "Schwarz Etienne",
    "Sea-God",
    "Sea-Gull",
    "Seah",
    "Seals",
    "Secret Labs",
    "Sector",
    "Seiko",
    "Sekonda",
    "Sellita",
    "Serket",
    "Sevenfriday",
    "Shanda",
    "Shinola",
    "Sicura",
    "Singer Reimagined",
    "Sinn",
    "SISU",
    "Sjoo Sandstrom",
    "Skagen",
    "Slava",
    "Slyde",
    "Smith & Bradley",
    "Snyper",
    "Soma",
    "Sony",
    "Sothis",
    "Speake-Marin",
    "SpeedUp",
    "Speidel",
    "Spero Lucem",
    "Spinnaker",
    "Sportourer",
    "Spyker",
    "Squale",
    "St. Dupont",
    "Steelcraft",
    "Stefan Johansson Vaxjo",
    "Steinhart",
    "Stella",
    "Sternglas",
    "Storm",
    "Stowa",
    "Stranger",
    "Straton",
    "Strom",
    "Stuckx",
    "Stuhrling",
    "Sturmanskie",
    "SuisseMecanica",
    "Suunto",
    "Swarovski",
    "Swatch",
    "Swiss Military",
    "Swiss Watch Company",
    "Swisstek",
    "Systeme Formel",
    "Tactico",
    "TAG Heuer",
    "Tavannes",
    "TB Buti",
    "Techne",
    "Technomarine",
    "Technos",
    "Tempest",
    "Temption",
    "Tempvs Compvtare",
    "Tendence",
    "Terra Cielo Mare",
    "Theorein",
    "Thomas Ninchritz",
    "Thomas Prescher",
    "Thorr",
    "Tiffany",
    "Timberland Watches",
    "Timex",
    "Tiret",
    "Tisell",
    "Tissot",
    "Titoni",
    "Titus",
    "Tockr",
    "Tokyo Flash",
    "Tokyo Street",
    "Tommy Hilfiger",
    "Tonino Lamborghini",
    "Torgoen",
    "Torrini",
    "Torsten Nagengast",
    "Tourby",
    "Tournaire",
    "Traser",
    "Trilobe",
    "Trotha",
    "TSAO",
    "Tsovet",
    "Tudor",
    "Tutima",
    "TW Steel",
    "TWCO",
    "Twelf X",
    "Twistiti",
    "TX TechnoLuxury",
    "U-Boat",
    "Ultramarine",
    "Ulysse Nardin",
    "Undone",
    "Uniform Wares",
    "Unikatuhren",
    "Unimatic",
    "Union Glashutte",
    "Uniq",
    "Universal Geneve",
    "Urban Jürgensen",
    "Urban Jurgensen & Sonner",
    "Urwerk",
    "UTS",
    "Vacheron Constantin",
    "Vaer",
    "Valbray",
    "Valentino",
    "Valerii Danevych",
    "Valpin",
    "Van Cleef & Arpels",
    "Vandaag",
    "Van Der Bauwede",
    "Van Ree",
    "Vangarde",
    "Vault",
    "VCXO",
    "Veldini",
    "Veni Vidi Vici",
    "Ventura",
    "Venturo",
    "Vero",
    "Versace",
    "Vertex",
    "Vianney Halter",
    "VicenTerra",
    "Viceroy",
    "Victorinox Swiss Army",
    "Villemont",
    "Vincent Calabrese",
    "Virata",
    "Visconti",
    "Vittorium",
    "Vixa",
    "Vogard",
    "Vollmer",
    "Volna",
    "Von Doren",
    "Vostok",
    "Votum",
    "Voutilainen",
    "Vulcain",
    "Wakmann",
    "Waltham",
    "Weiss Watch Company",
    "Welder",
    "Wellograph",
    "Wempe",
    "Wenger",
    "Werenbach",
    "WeWood",
    "Whitby Watch Co.",
    "Wilk Watchworks",
    "William L. 1985",
    "Withings",
    "Wittnauer",
    "WMT",
    "Wryst",
    "Wyler",
    "Wyler Vetta",
    "Xemex",
    "Xeric",
    "Xetum",
    "Xezo",
    "Yantar",
    "Yema",
    "YES",
    "Yes Watch",
    "Yonger & Bresson",
    "Yves Saint Laurent",
    "Zannetti",
    "Zeitwinkel",
    "Zelos",
    "Zenith",
    "Zeno-Watch Basel",
    "ZentRa",
    "Zeppelin",
    "Zero West",
    "Zodiac",
    "ZRC"
]

export default watchNamesList;